# Generated by Django 5.1.7 on 2025-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totoStore', '0002_remove_product_image_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. red, blue, black', max_length=30, null=True),
        ),
    ]
